global:
  environment: "production"
  logLevel: "warn"
  jwtKeyName: "jwt-secret"
  extraLabels:
    institution: "USAC"
    faculty: "Ingenieria"
    course: "Software-Avanzado"
    stage: "prod"

namespace:
  create: false
  name: "sa-p9"

postgresql:
  enabled: true
  persistence:
    size: "10Gi"
  resources:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: 250m
      memory: 512Mi

nats:
  enabled: true
  persistence:
    size: "5Gi"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: "mediconnect.usac.edu.gt"
      path: /
      pathType: Prefix

networkPolicies:
  enabled: true

resourceQuota:
  enabled: true
  requests:
    cpu: "8"
    memory: "8Gi"
  limits:
    cpu: "16"
    memory: "16Gi"
  pods: "50"

api-gateway:
  replicaCount: 3
  image:
    tag: "1.0.0"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  env:
    LOG_LEVEL: warn
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70

auth-service:
  replicaCount: 3
  image:
    tag: "1.0.0"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  env:
    LOG_LEVEL: warn
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 8
    targetCPUUtilizationPercentage: 70

doctors-service:
  replicaCount: 3
  image:
    tag: "1.0.0"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  env:
    LOG_LEVEL: warn
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 8
    targetCPUUtilizationPercentage: 70

appointments-service:
  replicaCount: 3
  image:
    tag: "1.0.0"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  env:
    LOG_LEVEL: warn
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 8
    targetCPUUtilizationPercentage: 70

lab-results-service:
  replicaCount: 3
  image:
    tag: "1.0.0"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  env:
    LOG_LEVEL: warn
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 8
    targetCPUUtilizationPercentage: 70

sealedSecrets:
  enabled: true
  encryptedUser: "AgBao+6/KikU977op9WUdySUNy4QG0ePKkxz1/c46oLjoH164tp4JtBd3i9mJ94mMCFNUQlU5U9q3Qrxl3C7h00kZ8B9u6AfBOPFF5a2wW6OzhKlAZPO7PU9tV0B+RK5wbsk3cAeEe54U++VCnYQObQc0U42k0TsBQzs9BtP1coAHIWu1ZqODSTGbVs+Akbi9PplaiGpPyAKRYY7h0KrCGB5sBoCfK7CTs/lON3VZAbNqUNcp5sh3MQ71PndKUMJqdEzZt4A+xSHiNM2okx6Bgkpd+u7+VCCy1HPyh/I7PUvuAgreyDlPW3DyodfNk6KaQbF9nvFe8cDDvorm0TjvpF/5UUfaR9brdyN+jOLTZGIeXRRwnyObjimLyhgNbosjZrJcntRXjCWOJfNQF2LWQdcvD61vwHvK1Zo8SVEWcsFJf6hmKMAVw4xzUZBBs4Kqyiqy/4S+MOgfdf38RTRTISw5zrxJDikYLD9oKz3nZieq5LLJr7AYXSJqgCDlOmJnvgx+mx4o4wsKlFJuZJBVx3o+W2r93MrAtFU2Ff3kJVi9UzCT31mkIqbKNoyp1NxEOnqMNM/04hUMBWcqd9dhZ+r4Ip/DFoahli+XrGVyCDfDhAI16XDAfQUy/GuSm7gpDm1E8Ec+lr0oJ6bF0oY7BP0FRMUBzXRcUii8O2S3HfFBcmT187Jya9Jd5UVoBsf1UWvgEcLDaG7UaTAdBBByY0ZOQ=="
  encryptedPassword: "AgBmftWxvyL8KF7nBgrAyCxY/7z+kjkoW12tR35v4qLfug5O/DX0n/qeQA/HTWa840VaCyokd6QYcCdc3wc04LkYAbD5HMD3vZJFLeTTPI3xejWq0GApuBn/yKdVc9yGwvwIIKVd6VDEvFKYtWfhGOqRO2EV+v1e6hHxKWCC3XXUwaUDE9MDcsTGXW/NzM2biY7fq9ypjQ4V7gcLXh+/PmKG0dHdq9+Cs4aFXYIlveI+tRRIc8Etd/4kvdIVlGjA/x0fJsr1gFzgIFhghtc4R85sNqUsHbvqL/UJfj/xgujOUHFyZ+eJm4X9AABZnC5dI5RGZOLXeH1PtSSUp9Qz3VukjMJyS07oTxar8ZS0ao6RT+AIgYmaGdmm60qevBj9d502e8TMpXP7lfC1lXGLHNs5clPxdC26IGjBtMIe3xQ8gUyDv1m1EJQiQs2UHLpdWC4z+1b7wZ8aoSuQu3n0El2iWXZd3fPOMTgFPC/koCXM4Y5pxlQH6kztnfmgeUVHy8anjVS7On7qEq7Nno26JwMrM6DkX7P/ZYBe4ED3Nh5cC8tbAHgMcwPSljd7NTZPxNVaSAVy95eLK2N6RQLOkeLJc5EUBWReFctoGe8dytcrnmyXcZznEiYk1kZpq83Gl/iTEtA2uvr4x1KTeNyV5Qu00vOGxwSgAYR/B96MQPDoKaGIaGqg2dYf9zHlNoe8nUeOv0MU2aHW2HZCA1NrGfkYYaB0RWtvcLrzZQ=="
  encryptedJwt: "AgAArzFmpiDw/Gr2/sRwnOhL/QIYltGDhpVT31vfoODuOb8kZGkmWXKCyb7LiYBKR+TcnjHjEOb+c8apuXC+jEqmFD8/Po6B8WMut6MNKZ/i6FdHdYV39IRBmM2ey2bXU20jIgf0W5lzzm6bOeMCkscwc7PjMkBT0WLQeCEOj3oPze2m1rXDv4BfKdd+CT/Oeth9BOz3dwcp2loPEHWJc0KuTM5RAHnvKPwsO6UMEjdlS4AQRnKlZRHNa0SiIh3eUhluyDpGfxmWwdo4i6Mj7BhokME7n5F4dMpht+N52Z6RJsCZNh0Dy7DfYBAASyXWoUz+rv3AdVoaXbU9r+d2jncUqkQ3DujT6e9AKvgcoRSFKgP7j4LDcJSqNd6lD5WyUy1bLKD7SPf8yE7/ziZsGNmLkFR6UZ7BJGl9AiQERrW62S9vKMbj2qXpSOVmji3+34sXPBA52dJWftBl4Gh6JqDoeNsYLZ+bRTcKpkm6oRUgufcJrlOWRyTlrsXO4oDlt5oajVnle3bZP9mgnKYa9xi3UDxNnlUmffM6Y5JMQimh34Etyu7v6Dr9rZx1JI5+0/Fbi+C6NDsmXwx5gnOgqJ4eV5uxdz0Fa2iaoZZYa2K1n7A2BuafTTk9+9rEBg/bcM4gOgEusHFtP2Lvj7ILw4Rm/GCDoCLTm6jFm4+uKATgjLWC8j5PePlPhPh5EOj9dtF/haHzq5axna/OTeGo9vwrILD9ax3a+VXLhSaf2s0avPo="

