global:
  environment: "production"
  logLevel: "warn"
  jwtKeyName: "jwt-secret"
  extraLabels:
    institution: "USAC"
    faculty: "Ingenieria"
    course: "Software-Avanzado"
    stage: "prod"

namespace:
  create: false
  name: "sa-p9"

postgresql:
  enabled: true
  persistence:
    size: "10Gi"
  resources:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: 250m
      memory: 512Mi

nats:
  enabled: true
  persistence:
    size: "5Gi"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: "mediconnect.usac.edu.gt"
      path: /
      pathType: Prefix

networkPolicies:
  enabled: true

resourceQuota:
  enabled: true
  requests:
    cpu: "8"
    memory: "8Gi"
  limits:
    cpu: "16"
    memory: "16Gi"
  pods: "50"

api-gateway:
  replicaCount: 1
  image:
    tag: "1.0.0"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  env:
    LOG_LEVEL: warn
  autoscaling:
    enabled: false
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70

auth-service:
  replicaCount: 1
  image:
    tag: "1.0.0"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  env:
    LOG_LEVEL: warn
  autoscaling:
    enabled: false
    minReplicas: 3
    maxReplicas: 8
    targetCPUUtilizationPercentage: 70

doctors-service:
  replicaCount: 1
  image:
    tag: "1.0.0"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  env:
    LOG_LEVEL: warn
  autoscaling:
    enabled: false
    minReplicas: 3
    maxReplicas: 8
    targetCPUUtilizationPercentage: 70

appointments-service:
  replicaCount: 1
  image:
    tag: "1.0.0"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  env:
    LOG_LEVEL: warn
  autoscaling:
    enabled: false
    minReplicas: 3
    maxReplicas: 8
    targetCPUUtilizationPercentage: 70

lab-results-service:
  replicaCount: 1
  image:
    tag: "1.0.0"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  env:
    LOG_LEVEL: warn
  autoscaling:
    enabled: false
    minReplicas: 3
    maxReplicas: 8
    targetCPUUtilizationPercentage: 70

sealedSecrets:
  enabled: true
  encryptedUser: "AgA8+rGz2/kh/W7Aa52pf9ewy0qHS5HVWBS4YcNMK7NFfxPmVKNbUX0o1o7IbxBDADfPb+ThSAa6IyP4Pqc1gSmVEax5wn1Zkfk2pEuSBjODZQSAdDqZmJMQlDJI0T/qgkjIV67t083CXLpE3v1mpRZnzMqqqfDANTfllzRFHHetpdaL5k2sETBGSeiBtq/x/XYptBvtTS6lRKkMmkn5+ePCu2WRokhBrGCrXbHNP2siQuMgE+7TAFdRLwkba/eS2srYbWJOO04xz+1HXt70rv9VYBas9Z0H538rHz5OvXR49k9n1UFKeGdTprzSf2aDDItG2KI9kHovqoi0cq1IuXPoDVmwJrvCO5Tt4Rt1DosMuilpMRB511aB9g5l3EG/LtMo1KQr2e56Sva9bqcyc2euia8hGddiM5mFw4NnKUzhPc4F51lHMQIgnvCEenm7L/+Q6WEO0wiN16mcztG4+RtsEaOOesnkCa0NBviCy3xww4Hw4EOkw4TDGz6rCYn8oOfn7DUeccnZAQoNpb5SGOLFYzCqdb4XeRA4g6BVJAA+40LIvDPjcUJyIfL1LZVxXHFzyWYM4vhqfOHsCOtrwwpnIKbVDV1RWLStboQUp9UQIXJiSn4voHgn2hiGKExxSnUCh1Y2b4T3iD1mHHDDqun8do9AqLyxTjoC9eAWW9OL2UJOlI/Viro4xNRhzoRavrZk9SUaUzJAJPIswIGaSqO/9g=="
  encryptedPassword: "AgB8t7RCQagmuikjIvfDzSs2qyB0+xXPeIW+mWouzeL7hl+W96tblwbUEBJjdSn+xkPm/t9SsJZryNdonBrYzOmokZauaNp3ZIr4tFPXubpKdcUPsQAaM0HwcIs1uBAbnyzIQ54+VRfjeeQI00OoSWEjUlqGCOjq5gGlq8QoU9+79gy0cz7Togox9137ME4EZG4Pc5iTkAY7U4s2gJG7BbYvw3s9XUHt9Yf4oaznbK3LQjUybUqbEvY2V8p+etH1tXlRoZ60nIra9tLunQVHX9AA/vfProO+0baP/0QIXA+rAl06dsqCHYmE8IyKe3AW8ef5ibhWJ6FN+Om4jUvuV+NlS7VY8y9DIP2a3RWuc6M4BBsrLqEmO4Pq4WXsVry+yN86Xzf+htrVemZJArnjZiOlu17GIqtdbOf66Uk7vXUwW9gFQzQ/zVv2cSL88n/udO2z3skGa39sEaajUCY26PLjSi85anKz0Cdk22jwtnotB8+4C17+7QUVfjRNPyNo0MmOjBc8jc2EXuf93UixavKJhJNFn5De6njb36u1dilWwNtc5lbrbPe1lgwJZD9opEXBme2aX3jsMOWPt8GfEE9A2zSodhLkSb3GRDFucxZ2j7o9YfG2t9yobGFfQgOLt9JGwgFsCHu94PR8zw5pzPTsaTRL57mGLAkqdrxCT/JH6Ez5vS/T0BxdKtxJ4kIfnJv6BTH16bhcbk+XPiZZviHQEdc8jXqYBGwDc3Hq"
  encryptedJwt: "AgCnohqOy4QKVhyBUnjdsU+YeqX9Ne1O2eNzFPu/T2OeUZdOOJAsN7si80b3rt7i7HhGu4tDfKsh41Fwr8SUyeGpLzNNRTMm8RqtxWlFntkDy/IzQwdT5yCmwadFbIUnmsNYKhivBYQoyWm8TMpXiEgj+fTUe7cGkbQxwPBqQY+cJ6a3N8WD/jhzpvF6ugkZ7k6OiQmQwkhjsG8OqQ6iolnwmrp33Y9tZ6GEUD28yVI3RdfhItNcNWbDzFswBkOrMLS+K+iKgadiidtwbdHNnNCHF7xW4ZdiCDFxeGZoVZu8vg/MD6Gi4LGyIfn9DA8bM5Z+FokdWzWvSo97YUEicdfEHNQMid8hJ9lEE/xB2mWdXJ3KDNU6BpmJCfVLv5IJGf0zD+4HVzFA4EFP1OZiGvT4ZmNU10H7locR79MursaV9/k0YGNKYGBYgA5KGhatguClGHL/ws8n91Wd5ETFjfmnXIyC940sQyW1z/qArO9sajm8z4+kuP3WVCB3yj3uDCPZvQONWUafDqTksgiCI75nA7nLabgs7+I1vsJLJ0hQ0w+VRbDX/rmefJ477++KxuExQgXCIjmsBelYQsAtvdDB5WIMQNWR9Jc5ziG7XDu/pj8Gwvk2mMgoycBu6Y+pE96hP2H1cTYoDSNLgDZsC3xxHUWMcGH4cZEylk5Ig2j2kt/5pK0oS8qf+cVlCAmLg32XBs6ymsB6LyU7e6RruwEturWooORyFxCcWsTMFNC3VcIKvom1"

