apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgresql-headless
  labels:
    {{- include "sa-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: 5432
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: sa-platform
    app.kubernetes.io/component: database
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nats
  labels:
    {{- include "sa-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: broker
spec:
  type: ClusterIP
  ports:
    - name: client
      port: 4222
      targetPort: 4222
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: sa-platform
    app.kubernetes.io/component: broker
